### ISSUE TITLE
View: When columns, alternatives or config variables (ProcessingWidget) are changed it is necessary to to update also the other components of the window.

### ISSUE THREAD

**Issue by Mikrischu** [einDamian/discrete-choice#25]
Example: You could define a column derivation after using the label already in an alternative. In that case the alternative error markers should be updated.
Suggestion: Implementation like for "Import Data" button in the FileMenu by @alice221927 (Alissa).
<img width="1112" alt="Bildschirmfoto 2023-07-19 um 22 43 13" src="https://github.com/einDamian/discrete-choice/assets/133114285/73e2022f-f627-4fe1-afec-5013df186be5">

**Comment by FliFlaFloo** [comment]
This should be done in the widget update pull request but the updating is not enough to change the error report on the availability condition. Even when updated previously mussing variables are marked. @Mikrischu any idea why?
