### ISSUE TITLE
EvaluationWidget: The result visualization seems seems not to work perfectly (I don't know why, I know it worked before).

### ISSUE THREAD

**Issue by Mikrischu** [einDamian/discrete-choice#43]
<img width="1193" alt="Bildschirmfoto 2023-07-20 um 23 44 06" src="https://github.com/einDamian/discrete-choice/assets/133114285/b3eb66b8-862f-42bf-8866-84ff04e1edab">

**Comment by alice221927** [comment]
See Pull request
