### ISSUE TITLE
EvaluationWidget: I got this, when I try to export an evaluation as CSV (wrong file format in EvaluationWidget.export)

### ISSUE THREAD

**Issue by Mikrischu** [einDamian/discrete-choice#49]
<img width="912" alt="Bildschirmfoto 2023-07-21 um 12 14 31" src="https://github.com/einDamian/discrete-choice/assets/133114285/33e4ff80-283d-4bf5-a538-ce27cc87e2d0">

**Comment by alice221927** [comment]
I think this is the result of trying to export the data to a csv file, which already exists.
Currently the file dialog is intended to select Directories only...

**Comment by alice221927** [comment]
the problem should no be fixed
